### PR TITLE
Update readme.

### PR DESCRIPTION
**Pull request by SamTov**
Updated the readme to look a bit more like a package

### CODE REVIEW

**Review by christophlohrmann — DISMISSED** [review]

**Comment by christophlohrmann** [comment]
the espresso build errors are exactly what I see on my local machine at the institute as well. We need to ask @jngrad how to fix this

**Comment by jngrad** [comment]
> the espresso build errors are exactly what I see on my local machine at the institute as well. We need to ask @jngrad how to fix this

@christophlohrmann I'm not sure why you're insisting on building ESPResSo with Python 3.8 :smile: The ESPResSo python branch (`git clone https://github.com/espressomd/espresso.git` in your workflow) only supports Python 3.9+. You already solved that issue on your workstation by setting up a Python 3.9 conda environment. In addition, `ubuntu-latest` in your workflow resolves to Ubuntu 22.04 since December 15 2022. This OS only provides Python 3.10 header files, which is also why Cython cannot process .pyx files on your workstation at the institute without a conda or virtual environment. In your workflow log file, pip seems to install Cython with the 3.8 header files, which is probably why CMake complains it can't find the 3.10 include directories.

I would recommend that you replace `pip install cython` in the workflow by `pip install -c requirements.txt cython` to avoid installing Cython 3.0, which is currently available on Pypi as a pre-release, and which we don't officially support yet. We added a range constraint in the ESPResSo requirements.txt only a week ago. Also, support for pip-installed Cython was introduced only last month (espressomd/espresso@4ec221db77b0cf246e06214c9b104a66dbcc1bdd). Regarding CMake 3.25, I didn't have an opportunity to thoroughly test it yet, because there is a known regression in 3.25.0 that negatively impacts its native CUDA support when Clang is used as the compiler. However, in an Ubuntu 22.04 Docker container, CMake 3.25 works fine with ESPResSo.

**Comment by SamTov** [comment]
> > the espresso build errors are exactly what I see on my local machine at the institute as well. We need to ask @jngrad how to fix this
> 
> @christophlohrmann I'm not sure why you're insisting on building ESPResSo with Python 3.8 smile The ESPResSo python branch (`git clone https://github.com/espressomd/espresso.git` in your workflow) only supports Python 3.9+. You already solved that issue on your workstation by setting up a Python 3.9 conda environment. In addition, `ubuntu-latest` in your workflow resolves to Ubuntu 22.04 since December 15 2022. This OS only provides Python 3.10 header files, which is also why Cython cannot process .pyx files on your workstation at the institute without a conda or virtual environment. In your workflow log file, pip seems to install Cython with the 3.8 header files, which is probably why CMake complains it can't find the 3.10 include directories.
> 
> I would recommend that you replace `pip install cython` in the workflow by `pip install -c requirements.txt cython` to avoid installing Cython 3.0, which is currently available on Pypi as a pre-release, and which we don't officially support yet. We added a range constraint in the ESPResSo requirements.txt only a week ago. Also, support for pip-installed Cython was introduced only last month ([espressomd/espresso@4ec221d](https://github.com/espressomd/espresso/commit/4ec221db77b0cf246e06214c9b104a66dbcc1bdd)). Regarding CMake 3.25, I didn't have an opportunity to thoroughly test it yet, because there is a known regression in 3.25.0 that negatively impacts its native CUDA support when Clang is used as the compiler. However, in an Ubuntu 22.04 Docker container, CMake 3.25 works fine with ESPResSo.

I am more than happy to use only >- 3.9.

**Comment by SamTov** [comment]
@jngrad does espresso now require fftw in the install? It used to be optional right?

**Comment by jngrad** [comment]
> @jngrad does espresso now require fftw in the install? It used to be optional right?

Still is. Use `-D ESPRESSO_BUILD_WITH_FFTW=OFF` if you don't need it.

By the way, using a rolling version of a dependency, here ESPResSo, is not ideal in the CI workflow of pull requests. Rolling versions are useful in the CI workflow of nightly builds on the main branch, because you want to be notified as soon as possible when a dependency breaks your build. In PRs, you probably want pinned dependencies, so that contributors are not affected by changes in dependencies. This can be achieved with a `git checkout <stable_commit>` after the git clone. This is what we do on ESPResSo:

```cmake
if(ESPRESSO_BUILD_WITH_WALBERLA)
  include(FetchContent)
  FetchContent_Declare(
    walberla
    GIT_REPOSITORY https://i10git.cs.fau.de/walberla/walberla.git
    GIT_TAG        01a28162ae1aacf7b96152c9f886ce54cc7f53ff
  )
```

**Comment by SamTov** [comment]
@christophlohrmann I have fixed the issues with the CI. It should all be fine now.

**Review by christophlohrmann — APPROVED** [review]

**Pull request merged**
