### PR TITLE
add const force

### PR DESCRIPTION
**Pull request by christophlohrmann**
Const flowfield does not play well with brownian thermostat due to double friction terms, so here is constant force instead

### CODE REVIEW

**Comment by christophlohrmann** [comment]
@SamTov do you have to review before CI starts??

**Comment by SamTov** [comment]
> @SamTov do you have to review before CI starts??

This isn't based on the CI branch so the workflow files aren't here yet.

**Review by SamTov — APPROVED** [review]
Nice additions, up to you whether you want to merge the CI in here first and then this into main or merge this one without running the tests. I don't mind either way, there should be no conflicts or at least, no bad ones.

**Review by SamTov — APPROVED** [review]
Looks great

**Pull request merged**
